### ISSUE TITLE
Trouble setting up the network

### ISSUE THREAD

**Issue by thehamdiaz** [uhl1k/Ricart-Agrawala-with-token#3]
I'm having trouble setting up the network of nodes.
in the `readme.md` file : `At first, you want to start the node, set its IP... ` there's no option to set the ip nor the port of the first node. And where do i find the Ansible script. Thank you. 
I'm using docker containers instead of VMs.

**Comment by uhl1k** [comment]
When I was looking at the code I realized this was not the final version. I fixed it by pushing new branch named `final` that should contain finished working code and made this branch default branch. I will add `readme.md` to this branch as well but I have other stuff to do so I don't know when will I get to it.

The version I uploaded asks for IP of the node and then IP address of any node in network if there is any. Ansible script is in `deploy.yml` but it is very basic, it just copies `.jar` file to the target machines and you probably would need to modify it to use with Docker. Aditionally, I found mistake on line 9 where it should be "dsa" and not "sa".

I'm sorry, it was my mistake not checking the code I uploaded but I had it on several remotes and just didn't check it properly. Hope you will find a way to make it work.

**Comment by uhl1k** [comment]
Moreover, when I was looking at the code I realized this was not the final version. I fixed it by pushing new branch named `final` that should contain finished working code and made this branch default branch. I will add `readme.md` to this branch as well but I have other stuff to do so I don't know when will I get to it. Hope you will find a way to make it work.

**Comment by uhl1k** [comment]
Finally, I uploaded the correct version in the `final` branch and written the readme. I also tested it and it is working properly. I am closing this issue.
